### PR TITLE
Allow to build with older OpenSSL versions (or LibreSSL).

### PR DESCRIPTION
**Pull request by falsovsky**
The attached patch allows **hopm** to build on OpenBSD again.

References to the fix: 
* https://github.com/edenhill/librdkafka/issues/3133#issuecomment-757868615
* https://wiki.openssl.org/index.php/Hostname_validation

This fixes issue #41

### CODE REVIEW

**Comment by miwob** [comment]
We can add the libressl workaround part, but support for older, eol openssl versions won't be re-added.

**Comment by falsovsky** [comment]
I think its the same @miwob . LibreSSL doesn't include those "new" functions.

So maybe just change the DEFINES ?

**Comment by miwob** [comment]
I think we're not doing anything here. From what I can see, SSL_set1_host does exist in OpenBSD 6.5. So whatever libressl version that was modern at this time (I think that was 2.9.1) and later should compile fine with hopm.

**Comment by miwob** [comment]
See https://github.com/libressl-portable/openbsd/blob/master/src/lib/libssl/ssl_lib.c#L458-L470

**Comment by falsovsky** [comment]
So its probably something related with includes. Or the linking libraries

**Comment by falsovsky** [comment]
@miwob the problem is in **SSL_set_hostflags**

```
lemonparty:~/irc/hopm$ uname -a
OpenBSD lemonparty 6.8 GENERIC.MP#0 amd64
lemonparty:~/irc/hopm$ man SSL_set_hostflags
man: No entry for SSL_set_hostflags in the manual.
```

**Comment by miwob** [comment]
A fix will be pushed soon. Please test and see if it works for you.

**Comment by falsovsky** [comment]
Just tried it, and it builds. Thanks for commiting.

**Comment by miwob** [comment]
Thanks for spotting!

**Pull request closed without merging**
